# name 可以自定义
name: 部署测试站点预览

# 触发条件：在 push 到 main/master 分支后，新的 Github 项目 应该都是 main，而之前的项目一般都是 master
on:
  push:
    branches:
      - Dev

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Cheakout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
  
      - name: 生成静态文件
        run: yarn build

     # 部署到 公开Dev页面
      - name: 部署
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:yzsong06/Vuepress-TakagiWikiPageDev.git
          BRANCH: main
          FOLDER: ./.vuepress/dist
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_DEV_KEY }}
