# name 可以自定义
name: 部署标准版站点

on:
  push:
    branches:
      - main

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Cheakout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
  
      - name: 生成静态文件
        run: yarn build

      # 部署到 公开页面
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:yzsong06/TakagiWikiSiteCNVuePage.git
          BRANCH: main
          FOLDER: ./.vuepress/dist
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
